# Session 11: Advanced Retrieval with LangChain

## Learning Objectives:

- Understand and implement multiple retrieval strategies for RAG
- Compare naive, BM25, multi-query, parent-document, contextual compression, ensemble, and semantic chunking approaches
- Build RAG chains over a health and wellness knowledge base using LangChain and QDrant

In the following notebook, we'll explore various methods of advanced retrieval using LangChain!

We'll touch on:

- Naive Retrieval
- Best-Matching 25 (BM25)
- Multi-Query Retrieval
- Parent-Document Retrieval
- Contextual Compression (a.k.a. Rerank)
- Ensemble Retrieval
- Semantic chunking

We'll also discuss how these methods impact performance on our set of documents with a simple RAG chain.

There will be two breakout rooms:

- 🤝 Breakout Room Part #1
  - Task 1: Getting Dependencies!
  - Task 2: Data Collection and Preparation
  - Task 3: Setting Up QDrant!
  - Task 4-10: Retrieval Strategies
- 🤝 Breakout Room Part #2
  - Activity: Evaluate with Ragas

---

# 🤝 Breakout Room Part #1

## Task 1: Getting Dependencies!

We're going to need a few specific LangChain community packages, like OpenAI (for our [LLM](https://platform.openai.com/docs/models) and [Embedding Model](https://platform.openai.com/docs/guides/embeddings)) and Cohere (for our [Reranker](https://cohere.com/rerank)).

We'll also provide our OpenAI key, as well as our Cohere API key.

> NOTE: Create a `.env` file in this directory with `OPENAI_API_KEY` and `COHERE_API_KEY` to avoid being prompted each time.

In [1]:
%reload_ext autoreload
%autoreload 2

In [2]:
import os
import getpass
from dotenv import load_dotenv

load_dotenv()

if not os.environ.get("OPENAI_API_KEY"):
    os.environ["OPENAI_API_KEY"] = getpass.getpass("Enter your OpenAI API Key:")

In [3]:
if not os.environ.get("COHERE_API_KEY"):
    os.environ["COHERE_API_KEY"] = getpass.getpass("Cohere API Key:")

## Task 2: Data Collection and Preparation

We'll be using our Health and Wellness Guide - a comprehensive resource covering exercise, nutrition, sleep, stress management, habits, and common health concerns.

### Data Preparation

We'll load the wellness guide as a single document, then split it into smaller chunks using a `RecursiveCharacterTextSplitter` for our vector store. We also keep the raw (unsplit) document for use with the Parent Document Retriever and Semantic Chunker later.

In [4]:
from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter

loader = TextLoader("data/HealthWellnessGuide.txt")
raw_docs = loader.load()

text_splitter = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=50)
wellness_docs = text_splitter.split_documents(raw_docs)

Let's verify our data was loaded and split correctly!

In [5]:
print(f"Raw documents: {len(raw_docs)}")
print(f"Split chunks: {len(wellness_docs)}")
print(f"\nExample chunk:\n{wellness_docs[0]}")

Raw documents: 1
Split chunks: 45

Example chunk:
page_content='The Personal Wellness Guide
A Comprehensive Resource for Health and Well-being

PART 1: EXERCISE AND MOVEMENT

Chapter 1: Understanding Exercise Basics

Exercise is one of the most important things you can do for your health. Regular physical activity can improve your brain health, help manage weight, reduce the risk of disease, strengthen bones and muscles, and improve your ability to do everyday activities.' metadata={'source': 'data/HealthWellnessGuide.txt'}

## Task 3: Setting up QDrant!

Now that we have our documents, let's create a QDrant VectorStore with the collection name "wellness_guide".

We'll leverage OpenAI's [`text-embedding-3-small`](https://openai.com/blog/new-embedding-models-and-api-updates) because it's a very powerful (and low-cost) embedding model.

> NOTE: We'll be creating additional vectorstores where necessary, but this pattern is still extremely useful.

In [6]:
from langchain_qdrant import QdrantVectorStore
from langchain_openai import OpenAIEmbeddings

embeddings = OpenAIEmbeddings(model="text-embedding-3-small")

vectorstore = QdrantVectorStore.from_documents(
    wellness_docs,
    embeddings,
    location=":memory:",
    collection_name="wellness_guide",
)

## Task 4: Naive RAG Chain

Since we're focusing on the "R" in RAG today - we'll create our Retriever first.

### R - Retrieval

This naive retriever will simply look at each review as a document, and use cosine-similarity to fetch the 10 most relevant documents.

> NOTE: We're choosing `10` as our `k` here to provide enough documents for our reranking process later

In [7]:
naive_retriever = vectorstore.as_retriever(search_kwargs={"k" : 10})

### A - Augmented

We're going to go with a standard prompt for our simple RAG chain today! Nothing fancy here, we want this to mostly be about the Retrieval process.

In [8]:
from langchain_core.prompts import ChatPromptTemplate

RAG_TEMPLATE = """\
You are a helpful and kind assistant. Use the context provided below to answer the question.

If you do not know the answer, or are unsure, say you don't know.

Query:
{question}

Context:
{context}
"""

rag_prompt = ChatPromptTemplate.from_template(RAG_TEMPLATE)

### G - Generation

We're going to leverage `gpt-4.1-nano` as our LLM today, as - again - we want this to largely be about the Retrieval process.

In [9]:
from langchain_openai import ChatOpenAI

chat_model = ChatOpenAI(model="gpt-4.1-nano")

### LCEL RAG Chain

We're going to use LCEL to construct our chain.

> NOTE: This chain will be exactly the same across the various examples with the exception of our Retriever!

In [10]:
from langchain_core.runnables import RunnablePassthrough
from operator import itemgetter
from langchain_core.output_parsers import StrOutputParser

naive_retrieval_chain = (
    # INVOKE CHAIN WITH: {"question" : "<<SOME USER QUESTION>>"}
    # "question" : populated by getting the value of the "question" key
    # "context"  : populated by getting the value of the "question" key and chaining it into the base_retriever
    {"context": itemgetter("question") | naive_retriever, "question": itemgetter("question")}
    # "context"  : is assigned to a RunnablePassthrough object (will not be called or considered in the next step)
    #              by getting the value of the "context" key from the previous step
    | RunnablePassthrough.assign(context=itemgetter("context"))
    # "response" : the "context" and "question" values are used to format our prompt object and then piped
    #              into the LLM and stored in a key called "response"
    # "context"  : populated by getting the value of the "context" key from the previous step
    | {"response": rag_prompt | chat_model, "context": itemgetter("context")}
)

Let's see how this simple chain does on a few different prompts.

> NOTE: You might think that we've cherry picked prompts that showcase the individual skill of each of the retrieval strategies - you'd be correct!

In [11]:
naive_retrieval_chain.invoke({"question" : "What exercises can help with lower back pain?"})["response"].content

'Certainly! Here are some exercises that can help alleviate lower back pain:\n\n1. **Cat-Cow Stretch**: Start on your hands and knees. Alternately arch your back up (like a cat) and then sag it down (like a cow). Perform 10-15 repetitions.\n\n2. **Bird Dog**: From hands and knees, extend opposite arm and leg while engaging your core. Hold each extension for 5 seconds, then switch sides. Do 10 repetitions per side.\n\n3. **Pelvic Tilts**: Lie on your back with knees bent. Flatten your back against the floor by tightening your abs and tilting your pelvis slightly upward. Hold for 10 seconds and repeat 8-12 times.\n\n4. **Partial Crunches**: Lie on your back with knees bent. Cross your arms over your chest, tighten your stomach muscles, and lift your shoulders off the floor. Hold briefly, then lower. Do 8-12 repetitions.\n\n5. **Knee-to-Chest Stretch**: Lie on your back, pull one knee toward your chest while keeping the other foot flat on the ground. Hold for 15-30 seconds, then switch legs.\n\nThese exercises gently stretch and strengthen the muscles supporting your lower back, which can help reduce pain and prevent future episodes. Always consult with a healthcare professional before starting new exercises, especially if you have ongoing back pain.'

In [12]:
naive_retrieval_chain.invoke({"question" : "How does sleep affect overall health?"})["response"].content

'Sleep plays a vital role in overall health by supporting physical repair, mental well-being, and cognitive function. During sleep, the body repairs tissues, consolidates memories, and releases hormones that regulate growth and appetite. Adequate sleep (7-9 hours per night for adults) is essential for strengthening the immune system, managing stress, maintaining a healthy weight, and ensuring optimal brain function. Poor sleep or insomnia can negatively impact these processes, leading to health issues such as weakened immunity, mental health concerns, and increased risk of chronic diseases. Therefore, practicing good sleep hygiene and creating an environment conducive to restful sleep are key strategies for promoting overall health.'

In [13]:
naive_retrieval_chain.invoke({"question" : "What are some natural remedies for stress and headaches?"})["response"].content

'Some natural remedies for stress and headaches include:\n\n- Drinking plenty of water to stay hydrated.\n- Applying a cold or warm compress to the head or neck.\n- Resting in a dark, quiet room.\n- Gently massaging the temples and neck.\n- Using essential oils like peppermint or lavender.\n- Engaging in relaxation techniques such as deep breathing, progressive muscle relaxation, or grounding exercises.\n- Taking short walks, preferably in nature.\n- Listening to calming music.\n\nThese methods can help alleviate stress and reduce headache symptoms naturally.'

Overall, this is not bad! Let's see if we can make it better!

## Task 5: Best-Matching 25 (BM25) Retriever

Taking a step back in time - [BM25](https://www.nowpublishers.com/article/Details/INR-019) is based on [Bag-Of-Words](https://en.wikipedia.org/wiki/Bag-of-words_model) which is a sparse representation of text.

In essence, it's a way to compare how similar two pieces of text are based on the words they both contain.

This retriever is very straightforward to set-up! Let's see it happen down below!

In [14]:
from langchain_community.retrievers import BM25Retriever

bm25_retriever = BM25Retriever.from_documents(wellness_docs)

We'll construct the same chain - only changing the retriever.

In [15]:
bm25_retrieval_chain = (
    {"context": itemgetter("question") | bm25_retriever, "question": itemgetter("question")}
    | RunnablePassthrough.assign(context=itemgetter("context"))
    | {"response": rag_prompt | chat_model, "context": itemgetter("context")}
)

Let's look at the responses!

In [16]:
bm25_retrieval_chain.invoke({"question" : "What exercises can help with lower back pain?"})["response"].content

'Exercises that can help with lower back pain include:\n\n- **Cat-Cow Stretch:** Start on your hands and knees. Alternate between arching your back up (cat) and letting it sag down (cow). Perform 10-15 repetitions.\n\n- **Bird Dog:** From hands and knees, extend opposite arm and leg while keeping your core engaged. Hold for 5 seconds, then switch sides. Do 10 repetitions per side.\n\n- **Pelvic Tilts:** Lie on your back with knees bent. Flatten your back against the floor by tightening your abdominal muscles and tilting your pelvis slightly upward. Hold for 10 seconds and repeat 8-12 times.\n\nThese gentle stretching and strengthening exercises can help alleviate lower back discomfort and potentially prevent future episodes.'

In [17]:
bm25_retrieval_chain.invoke({"question" : "How does sleep affect overall health?"})["response"].content

'Sleep significantly impacts overall health. Maintaining a regular sleep schedule and creating an optimal sleep environment—such as keeping the room cool, dark, and quiet—are important for quality sleep. Good sleep hygiene practices, including establishing relaxing bedtime routines and limiting screen time before bed, support better sleep. Adequate and restful sleep helps improve mood, energy levels, cognitive function, and immune health. Conversely, poor sleep or sleep disorders like insomnia can negatively affect overall wellness.'

In [18]:
bm25_retrieval_chain.invoke({"question" : "What are some natural remedies for stress and headaches?"})["response"].content

'Some natural remedies for stress include practicing relaxation techniques such as deep breathing exercises, meditation, and progressive muscle relaxation. For headaches, staying well-hydrated, managing stress, ensuring good sleep, and avoiding known triggers like certain foods can help. Herbal teas like chamomile or valerian root may also promote relaxation and reduce headache symptoms.'

It's not clear that this is better or worse, if only we had a way to test this (SPOILERS: We do, the second half of the notebook will cover this)

### ❓ Question #1:

Give an example query where BM25 is better than embeddings and justify your answer.

##### Answer:

Unlike the naive retriever methods that use cosine similarity for identifying similar embeddings, BM25 is an exact text match retriever. An example where BM25 is better is in identifying error codes in software logs: "Find all instances of IndexError in yesterday's logs." The retriever will specifically search for logs where the exact `IndexError` word (at a token level) shows up. If there was a corpus of additional troubleshooting documents and a dense retriever is used instead, this query may find items having to do with any old error, not just the `IndexError`. 

Moreover, in the embedding space, `KeyError` and `TypeError` are also close to `IndexError`, so a dense retriever may return those options. To combat this, the exact token `IndexError` is retrieved when using BM25.

## Task 6: Contextual Compression (Using Reranking)

Contextual Compression is a fairly straightforward idea: We want to "compress" our retrieved context into just the most useful bits.

There are a few ways we can achieve this - but we're going to look at a specific example called reranking.

The basic idea here is this:

- We retrieve lots of documents that are very likely related to our query vector
- We "compress" those documents into a smaller set of *more* related documents using a reranking algorithm.

We'll be leveraging Cohere's Rerank model for our reranker today!

All we need to do is the following:

- Create a basic retriever
- Create a compressor (reranker, in this case)

That's it!

Let's see it in the code below!

In [19]:
from langchain.retrievers.contextual_compression import ContextualCompressionRetriever
from langchain_cohere import CohereRerank

compressor = CohereRerank(model="rerank-v3.5")
compression_retriever = ContextualCompressionRetriever(
    base_compressor=compressor, base_retriever=naive_retriever
)

Let's create our chain again, and see how this does!

In [20]:
contextual_compression_retrieval_chain = (
    {"context": itemgetter("question") | compression_retriever, "question": itemgetter("question")}
    | RunnablePassthrough.assign(context=itemgetter("context"))
    | {"response": rag_prompt | chat_model, "context": itemgetter("context")}
)

In [21]:
contextual_compression_retrieval_chain.invoke({"question" : "What exercises can help with lower back pain?"})["response"].content

'Some exercises that can help with lower back pain include the Cat-Cow Stretch, Bird Dog, and Pelvic Tilts. These gentle stretching and strengthening exercises are recommended to alleviate discomfort and prevent future episodes.'

In [22]:
contextual_compression_retrieval_chain.invoke({"question" : "How does sleep affect overall health?"})["response"].content

'Sleep has a significant impact on overall health. It is essential for physical repair, mental well-being, and cognitive function. During sleep, the body repairs tissues, consolidates memories, and releases hormones that regulate growth and appetite. Getting adequate sleep, typically 7-9 hours per night, in a proper environment (cool, dark, quiet, comfortable) helps ensure these processes occur effectively. Poor sleep or sleep disorders like insomnia can negatively affect health, making quality sleep a crucial component of overall well-being.'

In [23]:
contextual_compression_retrieval_chain.invoke({"question" : "What are some natural remedies for stress and headaches?"})["response"].content

'Some natural remedies for stress and headaches include practicing deep breathing exercises, progressive muscle relaxation, and grounding techniques to reduce stress. For headaches specifically, remedies include drinking plenty of water to stay hydrated, applying cold or warm compresses to the head or neck, resting in a dark, quiet room, gently massaging the temples and neck, using peppermint or lavender essential oils, and maintaining a regular sleep schedule.'

We'll need to rely on something like Ragas to help us get a better sense of how this is performing overall - but it "feels" better!

## Task 7: Multi-Query Retriever

Typically in RAG we have a single query - the one provided by the user.

What if we had....more than one query!

In essence, a Multi-Query Retriever works by:

1. Taking the original user query and creating `n` number of new user queries using an LLM.
2. Retrieving documents for each query.
3. Using all unique retrieved documents as context

So, how is it to set-up? Not bad! Let's see it down below!

In [24]:
from langchain.retrievers.multi_query import MultiQueryRetriever

multi_query_retriever = MultiQueryRetriever.from_llm(
    retriever=naive_retriever, llm=chat_model
)

In [25]:
multi_query_retrieval_chain = (
    {"context": itemgetter("question") | multi_query_retriever, "question": itemgetter("question")}
    | RunnablePassthrough.assign(context=itemgetter("context"))
    | {"response": rag_prompt | chat_model, "context": itemgetter("context")}
)

In [26]:
multi_query_retrieval_chain.invoke({"question" : "What exercises can help with lower back pain?"})["response"].content

'Exercises that can help with lower back pain include:\n\n- Cat-Cow Stretch: Start on hands and knees, alternate between arching your back up (cat) and letting it sag down (cow). Do 10-15 repetitions.\n- Bird Dog: From hands and knees, extend opposite arm and leg while keeping your core engaged. Hold for 5 seconds, then switch sides. Perform 10 repetitions per side.\n- Partial Crunches: Lie on your back with knees bent, cross arms over chest, tighten stomach muscles and raise shoulders off the floor. Hold briefly, then lower. Do 8-12 repetitions.\n- Knee-to-Chest Stretch: Lie on your back, pull one knee toward your chest while keeping the other foot flat. Hold for 15-30 seconds, then switch legs.\n- Pelvic Tilts: Lie on your back with knees bent, flatten your back against the floor by tightening your abs and tilting your pelvis slightly. Hold for 10 seconds and repeat 8-12 times.\n\nThese exercises are recommended for alleviating lower back pain and can be performed regularly to help improve back strength and flexibility.'

In [27]:
multi_query_retrieval_chain.invoke({"question" : "How does sleep affect overall health?"})["response"].content

'Sleep has a significant impact on overall health. It is essential for physical recovery, mental well-being, and cognitive function. During sleep, the body repairs tissues, consolidates memories, and releases hormones that regulate growth and appetite. Adequate sleep—typically 7 to 9 hours per night—is linked to a healthier immune system, better mood, improved concentration, and longer lifespan. Sleep quality can be enhanced by practices such as maintaining a consistent schedule, creating an optimal sleep environment, and adopting relaxing bedtime routines. Conversely, poor sleep or sleep disturbances like insomnia can negatively affect physical health, mental health, and daily functioning.'

In [28]:
multi_query_retrieval_chain.invoke({"question" : "What are some natural remedies for stress and headaches?"})["response"].content

'Some natural remedies for stress and headaches include:\n\n- Deep breathing exercises (e.g., inhale for 4 counts, hold for 4, exhale for 4)\n- Progressive muscle relaxation, tensing and releasing muscle groups\n- Grounding techniques, such as identifying five things you see, four you hear, three you feel, two you smell, and one you taste\n- Taking short walks, preferably in nature\n- Listening to calming music\n- Drinking water to stay hydrated\n- Applying cold or warm compresses to the head or neck\n- Resting in a dark, quiet room\n- Gentle massage of the temples and neck\n- Using essential oils like peppermint or lavender\n\nFor stress relief and headache management, these natural methods can be effective in promoting relaxation and reducing symptoms.'

### ❓ Question #2:

Explain how generating multiple reformulations of a user query can improve recall.

##### Answer:

In RAG, recall measures the ability of the retriever to find all documents relevant to the user query. Generating multiple versions of the user query creates a wider net that allows the retriever to cover more "surface area" and find more related documents. Sometimes a RAG system might infer a different understanding of the query and incorrectly pull out wrong documents. This reformulation ensures the broadest understanding of the query and thereby finds the broadest set of related documents, thereby increasing recall.

## Task 8: Parent Document Retriever

A "small-to-big" strategy - the Parent Document Retriever works based on a simple strategy:

1. We split the full document into large "parent" chunks (e.g. 2000 characters).
2. Each parent chunk is further split into smaller "child" chunks (e.g. 400 characters).
3. The child chunks are stored in a VectorStore, while the parent chunks are stored in an in-memory docstore.
4. When we query our Retriever, we do a similarity search comparing our query vector to the child chunks.
5. Instead of returning the child chunks, we return their associated parent chunks.

The basic idea is:

- **Search** for small, focused chunks (better semantic matching)
- **Return** big chunks (richer surrounding context)

The intuition is that we're likely to find the most relevant information by limiting the amount of semantic information encoded in each embedding vector - but we're likely to miss relevant surrounding context if we only use that information.

Let's start by defining our parent and child splitters.

In [29]:
from langchain.retrievers import ParentDocumentRetriever
from langchain.storage import InMemoryStore
from langchain_text_splitters import RecursiveCharacterTextSplitter
from qdrant_client import QdrantClient, models

parent_splitter = RecursiveCharacterTextSplitter(chunk_size=2000, chunk_overlap=200)
child_splitter = RecursiveCharacterTextSplitter(chunk_size=400, chunk_overlap=50)

We'll need to set up a new QDrant vectorstore - and we'll use another useful pattern to do so!

> NOTE: We are manually defining our embedding dimension, you'll need to change this if you're using a different embedding model.

In [30]:
from langchain_qdrant import QdrantVectorStore

client = QdrantClient(location=":memory:")

client.create_collection(
    collection_name="wellness_parent_child",
    vectors_config=models.VectorParams(size=1536, distance=models.Distance.COSINE)
)

parent_document_vectorstore = QdrantVectorStore(
    collection_name="wellness_parent_child", embedding=OpenAIEmbeddings(model="text-embedding-3-small"), client=client
)

Now we can create our `InMemoryStore` that will hold our "parent documents" - and build our retriever!

In [31]:
store = InMemoryStore()

parent_document_retriever = ParentDocumentRetriever(
    vectorstore=parent_document_vectorstore,
    docstore=store,
    child_splitter=child_splitter,
    parent_splitter=parent_splitter,
)

By default, this is empty as we haven't added any documents - let's add some now!

In [32]:
parent_document_retriever.add_documents(raw_docs, ids=None)

We'll create the same chain we did before - but substitute our new `parent_document_retriever`.

In [33]:
parent_document_retrieval_chain = (
    {"context": itemgetter("question") | parent_document_retriever, "question": itemgetter("question")}
    | RunnablePassthrough.assign(context=itemgetter("context"))
    | {"response": rag_prompt | chat_model, "context": itemgetter("context")}
)

Let's give it a whirl!

In [34]:
parent_document_retrieval_chain.invoke({"question" : "What exercises can help with lower back pain?"})["response"].content

'To help with lower back pain, gentle stretching and strengthening exercises are recommended. Some effective exercises include:\n\n- **Cat-Cow Stretch:** On hands and knees, alternate arching your back up (cat) and letting it sag down (cow). Perform 10-15 repetitions.\n- **Bird Dog:** From hands and knees, extend opposite arm and leg while keeping your core engaged. Hold for 5 seconds, then switch sides. Do 10 repetitions per side.\n- **Partial Crunches:** Lie on your back with knees bent, arms crossed over chest, tighten your stomach muscles, and lift your shoulders off the floor. Do 8-12 repetitions.\n- **Knee-to-Chest Stretch:** Lie on your back, pull one knee toward your chest while keeping the other foot flat. Hold for 15-30 seconds, then switch legs.\n- **Pelvic Tilts:** Lie on your back with knees bent, flatten your back against the floor by tightening your abs and tilting your pelvis up slightly. Hold for 10 seconds and repeat 8-12 times.\n\nAlways consult a healthcare professional before starting any new exercise routine, especially if you have ongoing pain or other health issues.'

In [35]:
parent_document_retrieval_chain.invoke({"question" : "How does sleep affect overall health?"})["response"].content

'Sleep has a significant impact on overall health. It is essential for physical health, mental well-being, and cognitive function. During sleep, the body repairs tissues, consolidates memories, and releases hormones that regulate growth and appetite. Adults typically need 7-9 hours of sleep per night to maintain optimal health. Good sleep quality supports immune function, energy levels, and emotional stability, while poor sleep can lead to issues such as fatigue, headaches, mood disturbances, and a weakened immune system. Therefore, prioritizing restful, consistent sleep is a crucial component of maintaining overall health.'

In [36]:
parent_document_retrieval_chain.invoke({"question" : "What are some natural remedies for stress and headaches?"})["response"].content

'Some natural remedies for stress and headaches include practicing deep breathing exercises, engaging in mindfulness or meditation, doing gentle stretching or yoga, taking a warm bath, and listening to calming music. For headaches specifically, remedies such as staying hydrated by drinking water, applying cold or warm compresses to the head or neck, resting in a dark, quiet room, gently massaging the temples and neck, and using essential oils like peppermint or lavender can be helpful.'

Overall, the performance *seems* largely the same. We can leverage a tool like [Ragas]() to more effectively answer the question about the performance.

## Task 9: Ensemble Retriever

In brief, an Ensemble Retriever simply takes 2, or more, retrievers and combines their retrieved documents based on a rank-fusion algorithm.

In this case - we're using the [Reciprocal Rank Fusion](https://plg.uwaterloo.ca/~gvcormac/cormacksigir09-rrf.pdf) algorithm.

Setting it up is as easy as providing a list of our desired retrievers - and the weights for each retriever.

In [37]:
from langchain.retrievers import EnsembleRetriever

retriever_list = [bm25_retriever, naive_retriever, parent_document_retriever, compression_retriever, multi_query_retriever]
equal_weighting = [1/len(retriever_list)] * len(retriever_list)

ensemble_retriever = EnsembleRetriever(
    retrievers=retriever_list, weights=equal_weighting
)

We'll pack *all* of these retrievers together in an ensemble.

In [38]:
ensemble_retrieval_chain = (
    {"context": itemgetter("question") | ensemble_retriever, "question": itemgetter("question")}
    | RunnablePassthrough.assign(context=itemgetter("context"))
    | {"response": rag_prompt | chat_model, "context": itemgetter("context")}
)

Let's look at our results!

In [39]:
ensemble_retrieval_chain.invoke({"question" : "What exercises can help with lower back pain?"})["response"].content

"Exercises that can help with lower back pain include:\n\n- Cat-Cow Stretch: Start on hands and knees, alternate between arching your back up (cat) and letting it sag down (cow). Perform 10-15 repetitions.\n\n- Bird Dog: From hands and knees, extend opposite arm and leg while keeping your core engaged. Hold for 5 seconds, then switch sides. Do 10 repetitions per side.\n\n- Pelvic Tilts: Lie on your back with knees bent, flatten your back against the floor by tightening your abs and tilting the pelvis up slightly. Hold for 10 seconds and repeat 8-12 times.\n\n- Partial Crunches: Lie on your back with knees bent, cross arms over your chest, tighten your stomach muscles, and raise your shoulders off the floor. Hold briefly, then lower. Complete 8-12 repetitions.\n\n- Knee-to-Chest Stretch: Lie on your back, pull one knee toward your chest while keeping the other foot flat on the ground. Hold for 15-30 seconds and switch legs.\n\nThese exercises can help alleviate discomfort and prevent future episodes of lower back pain. However, it's always a good idea to consult with a healthcare professional before starting new exercise routines, especially if you have existing health concerns."

In [40]:
ensemble_retrieval_chain.invoke({"question" : "How does sleep affect overall health?"})["response"].content

'Sleep significantly impacts overall health in multiple ways. It is essential for physical restoration, as the body repairs tissues and regenerates cells during sleep. Sleep also supports mental well-being by helping with memory consolidation and emotional regulation. Additionally, proper sleep regulates hormone release, including those controlling growth and appetite. Adequate sleep (7-9 hours per night) and good sleep hygiene—such as maintaining a consistent schedule, creating a comfortable sleep environment, and managing insomnia—are key practices that contribute to better health, mood, cognitive function, and immune system strength. Conversely, poor sleep can lead to health issues such as weakened immunity, mental health problems, impaired cognitive function, and increased risk of chronic conditions.'

In [41]:
ensemble_retrieval_chain.invoke({"question" : "What are some natural remedies for stress and headaches?"})["response"].content

'Some natural remedies for stress and headaches include:\n\n- Deep breathing exercises (e.g., inhaling for 4 counts, holding, then exhaling)\n- Progressive muscle relaxation, tensing and releasing muscle groups from toes to head\n- Grounding techniques, such as naming things you see, hear, feel, smell, and taste\n- Taking short walks, preferably in nature\n- Listening to calming music\n- Drinking water to stay hydrated\n- Applying cold or warm compresses to the head or neck\n- Resting in a dark, quiet room\n- Gentle massage of temples and neck\n- Using essential oils like peppermint or lavender\n- Maintaining a regular sleep schedule\n- Limiting screen time before bed\n- Practicing mindfulness and meditation\n\nThese approaches can help reduce stress and alleviate headache symptoms naturally.'

## Task 10: Semantic Chunking

While this is not a retrieval method - it *is* an effective way of increasing retrieval performance on corpora that have clean semantic breaks in them.

Essentially, Semantic Chunking is implemented by:

1. Embedding all sentences in the corpus.
2. Combining or splitting sequences of sentences based on their semantic similarity based on a number of [possible thresholding methods](https://python.langchain.com/docs/how_to/semantic-chunker/):
  - `percentile`
  - `standard_deviation`
  - `interquartile`
  - `gradient`
3. Each sequence of related sentences is kept as a document!

Let's see how to implement this!

We'll use the `percentile` thresholding method for this example which will:

Calculate all distances between sentences, and then break apart sequences of setences that exceed a given percentile among all distances.

In [42]:
from langchain_experimental.text_splitter import SemanticChunker

semantic_chunker = SemanticChunker(
    embeddings,
    breakpoint_threshold_type="percentile"
)

Now we can split our documents.

In [43]:
semantic_documents = semantic_chunker.split_documents(raw_docs)

Let's create a new vector store.

In [44]:
semantic_vectorstore = QdrantVectorStore.from_documents(
    semantic_documents,
    embeddings,
    location=":memory:",
    collection_name="wellness_guide_semantic_chunks"
)

We'll use naive retrieval for this example.

In [45]:
semantic_retriever = semantic_vectorstore.as_retriever(search_kwargs={"k" : 10})

Finally we can create our classic chain!

In [46]:
semantic_retrieval_chain = (
    {"context": itemgetter("question") | semantic_retriever, "question": itemgetter("question")}
    | RunnablePassthrough.assign(context=itemgetter("context"))
    | {"response": rag_prompt | chat_model, "context": itemgetter("context")}
)

And view the results!

In [47]:
semantic_retrieval_chain.invoke({"question" : "What exercises can help with lower back pain?"})["response"].content

'The exercises that can help with lower back pain include:\n\n- **Cat-Cow Stretch:** Start on your hands and knees, alternate between arching your back up (cat) and letting it sag down (cow). Do 10-15 repetitions.\n\n- **Partial Crunches:** Lie on your back with knees bent, cross your arms over your chest, tighten your stomach muscles, and lift your shoulders off the floor. Hold briefly, then lower. Do 8-12 repetitions.\n\n- **Knee-to-Chest Stretch:** Lie on your back, pull one knee toward your chest while keeping the other foot flat. Hold for 15-30 seconds, then switch legs.\n\n- **Pelvic Tilts:** Lie on your back with knees bent, flatten your back against the floor by tightening your abs and tilting your pelvis up slightly. Hold for 10 seconds, repeat 8-12 times.\n\n- **Bird Dog:** From hands and knees, extend opposite arm and leg while keeping your core engaged. Hold for 5 seconds, then switch sides.\n\nThese gentle stretches and strengthening exercises can alleviate discomfort and help prevent future episodes of lower back pain.'

In [48]:
semantic_retrieval_chain.invoke({"question" : "How does sleep affect overall health?"})["response"].content

'Sleep significantly impacts overall health in several vital ways. During sleep, the body repairs tissues, consolidates memories, and releases hormones that regulate growth and appetite. Adequate sleep (typically 7-9 hours for adults) supports physical health, mental well-being, and cognitive functions. Good sleep hygiene practices—such as maintaining a consistent sleep schedule, creating a relaxing bedtime routine, and optimizing the sleep environment—are essential for achieving quality rest. Poor sleep or insomnia can lead to issues like fatigue, difficulty concentrating, weakened immune function, increased risk of chronic conditions, and mental health problems. Therefore, prioritizing regular, restful sleep is fundamental to maintaining overall health and wellness.'

In [49]:
semantic_retrieval_chain.invoke({"question" : "What are some natural remedies for stress and headaches?"})["response"].content

'Some natural remedies for stress and headaches include:\n\n- Deep breathing exercises: Inhale for 4 counts, hold for 4, exhale for 4 to promote relaxation.\n- Progressive muscle relaxation: Tense and release different muscle groups to reduce tension.\n- Grounding techniques: Identify things you see, hear, feel, smell, and taste to center yourself.\n- Short walks in nature or outside for fresh air and a mental break.\n- Listening to calming music.\n- Hydration: Drinking plenty of water to prevent dehydration which can trigger headaches.\n- Applying cold or warm compresses to the head or neck.\n- Gentle massage of temples and neck muscles.\n- Using essential oils such as peppermint or lavender.\n- Ensuring proper sleep habits and maintaining a consistent sleep schedule.\n- Managing stress through mindfulness and meditation practices.\n\nThese approaches are natural and can be effective in managing stress and headaches.'

### ❓ Question #3:

If sentences are short and highly repetitive (e.g., FAQs), how might semantic chunking behave, and how would you adjust the algorithm?

##### Answer:

Semantic chunking splits a corpus based on similar semantic ideas or meanings. The text in an FAQ section of a document, which are usually short and repititive, will likely not be semantically different enough. This means the FAQ section may be one single semantic chunk, which could be undesirable for token efficiency and effective context retrieval. It's also possible that since everything looks very similar, small word choices in the text may increase the "signal to noise ratio", thereby causing too much chunking/splitting to occur. 

If we know ahead of time that FAQs need to be properly chunked, there are a few adjustment we can make to the algorithm:
- Split the FAQs so that each semantic chunk contains a Question and Answer. To do this, we can look for paired Question/Answers, numbering or Q/A headers, or punctuation (like question marks).
- Introduce a minimum chunk size to reduce over-chunking
- Add metadata for different sections within FAQs so that retrieval methods can more easily find the right context

---

# 🤝 Breakout Room Part #2

### 🏗️ Activity #1:

Your task is to evaluate the various Retriever methods against each other.

You are expected to:

1. Create a "golden dataset"
 - Use Synthetic Data Generation (powered by Ragas, or otherwise) to create this dataset
2. Evaluate each retriever with *retriever specific* Ragas metrics
 - Semantic Chunking is not considered a retriever method and will not be required for marks, but you may find it useful to do a "semantic chunking on" vs. "semantic chunking off" comparison between them
3. Compile these in a list and write a small paragraph about which is best for this particular data and why.

Your analysis should factor in:
  - Cost
  - Latency
  - Performance

> NOTE: This is **NOT** required to be completed in class. Please spend time in your breakout rooms creating a plan before moving on to writing code.

##### HINTS:

- LangSmith provides detailed information about latency and cost.

### Create Golden Dataset using SDG

In [ ]:
from openai import OpenAI
from ragas.embeddings import LangchainEmbeddingsWrapper
from ragas.llms import LangchainLLMWrapper, llm_factory
from ragas.embeddings.base import embedding_factory
from ragas.testset import TestsetGenerator
from ragas.testset.synthesizers.single_hop.specific import SingleHopSpecificQuerySynthesizer


generator_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4.1"))
generator_embeddings = LangchainEmbeddingsWrapper(OpenAIEmbeddings())

generator = TestsetGenerator(llm=generator_llm, embedding_model=generator_embeddings)
single_hop_distribution = [
    (SingleHopSpecificQuerySynthesizer(llm=generator_llm, llm_context=generator.llm_context), 1.0)
]

dataset = generator.generate_with_langchain_docs(
    raw_docs,
    testset_size=10,
    query_distribution=single_hop_distribution,
)

/var/folders/b8/jbm0jh5162z101vvqr99rs9r0000gn/T/ipykernel_30895/918644550.py:22: DeprecationWarning: LangchainLLMWrapper is deprecated and will be removed in a future version. Use llm_factory instead: from openai import OpenAI; from ragas.llms import llm_factory; llm = llm_factory('gpt-4o-mini', client=OpenAI(api_key='...'))
  generator_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4.1"))
/var/folders/b8/jbm0jh5162z101vvqr99rs9r0000gn/T/ipykernel_30895/918644550.py:23: DeprecationWarning: LangchainEmbeddingsWrapper is deprecated and will be removed in a future version. Use the modern embedding providers instead: embedding_factory('openai', model='text-embedding-3-small', client=openai_client) or from ragas.embeddings import OpenAIEmbeddings, GoogleEmbeddings, HuggingFaceEmbeddings
  generator_embeddings = LangchainEmbeddingsWrapper(OpenAIEmbeddings())

Applying HeadlinesExtractor:   0%|          | 0/1 [00:00<?, ?it/s]

Applying HeadlineSplitter:   0%|          | 0/1 [00:00<?, ?it/s]

Applying SummaryExtractor:   0%|          | 0/1 [00:00<?, ?it/s]

Applying CustomNodeFilter:   0%|          | 0/5 [00:00<?, ?it/s]

Applying EmbeddingExtractor:   0%|          | 0/1 [00:00<?, ?it/s]

Applying ThemesExtractor:   0%|          | 0/4 [00:00<?, ?it/s]

Applying NERExtractor:   0%|          | 0/4 [00:00<?, ?it/s]

Applying CosineSimilarityBuilder:   0%|          | 0/1 [00:00<?, ?it/s]

Applying OverlapScoreBuilder:   0%|          | 0/1 [00:00<?, ?it/s]

Generating personas:   0%|          | 0/1 [00:00<?, ?it/s]

Generating Scenarios:   0%|          | 0/1 [00:00<?, ?it/s]

Generating Samples:   0%|          | 0/12 [00:00<?, ?it/s]

### Evaluate Retrievers

Evaluating the 6 different retrievers using 4 retriever-specific metrics:
- Context Recall
- Context Precision
- Context Entity Recall
- Noise Sensitivity

These metrics are only focused on how well the retrivers perform and they roughly answer the question "Did the retriever get the right context?". These metrics do not depend on the LLM.

In [63]:
# Evaluate the retrievers
from src.ragas_utils import run_ragas_evaluation, compare_ragas_results

# Create a list of all retriever chains
retriever_chains = {
    "Naive Retrieval" : naive_retrieval_chain,
    "BM25 Retrieval" : bm25_retrieval_chain,
    "Contextual Compression Retrieval" : contextual_compression_retrieval_chain,
    "Multi-Query Retrieval" : multi_query_retrieval_chain,
    "Parent Document Retrieval" : parent_document_retrieval_chain,
    "Ensemble Retrieval" : ensemble_retrieval_chain
}

# Initialize a list to store Ragas metrics
ragas_metrics = []

for retriever_name, retriever_chain in retriever_chains.items():
    print(f"Running Ragas evaluation for {retriever_name}...")
    ragas_evals = run_ragas_evaluation(retriever_chain, retriever_name, dataset)
    ragas_metrics.append(ragas_evals)

Running Ragas evaluation for Naive Retrieval...

Evaluating:   0%|          | 0/48 [00:00<?, ?it/s]

Exception raised in Job[3]: TimeoutError()
Exception raised in Job[7]: TimeoutError()
Exception raised in Job[11]: TimeoutError()
Exception raised in Job[19]: TimeoutError()
Exception raised in Job[23]: TimeoutError()
Exception raised in Job[27]: TimeoutError()
Exception raised in Job[31]: TimeoutError()
Exception raised in Job[43]: TimeoutError()

Running Ragas evaluation for BM25 Retrieval...

Evaluating:   0%|          | 0/48 [00:00<?, ?it/s]

Running Ragas evaluation for Contextual Compression Retrieval...

Evaluating:   0%|          | 0/48 [00:00<?, ?it/s]

Running Ragas evaluation for Multi-Query Retrieval...

Evaluating:   0%|          | 0/48 [00:00<?, ?it/s]

Exception raised in Job[3]: TimeoutError()
Exception raised in Job[7]: TimeoutError()
Exception raised in Job[11]: TimeoutError()
Exception raised in Job[19]: TimeoutError()
Exception raised in Job[23]: TimeoutError()
Exception raised in Job[27]: TimeoutError()
Exception raised in Job[31]: TimeoutError()
Exception raised in Job[35]: TimeoutError()
Exception raised in Job[43]: TimeoutError()

Running Ragas evaluation for Parent Document Retrieval...

Evaluating:   0%|          | 0/48 [00:00<?, ?it/s]

Running Ragas evaluation for Ensemble Retrieval...

Evaluating:   0%|          | 0/48 [00:00<?, ?it/s]

Exception raised in Job[3]: TimeoutError()
Exception raised in Job[11]: TimeoutError()
Exception raised in Job[15]: TimeoutError()
Exception raised in Job[7]: TimeoutError()
Exception raised in Job[19]: TimeoutError()
Exception raised in Job[23]: TimeoutError()
Exception raised in Job[27]: TimeoutError()
Exception raised in Job[31]: TimeoutError()
Exception raised in Job[35]: TimeoutError()
Exception raised in Job[43]: TimeoutError()

### Compare Ragas metrics across retrievers

In [ ]:
comparison_df = compare_ragas_results(ragas_metrics)
comparison_df

,context_recall,context_precision,context_entity_recall,noise_sensitivity(mode=relevant)
Naive Retrieval,1.000,0.878,0.544,0.170
BM25 Retrieval,0.771,0.583,0.487,0.077
Contextual Compression Retrieval,0.958,0.861,0.491,0.053
Multi-Query Retrieval,0.958,0.881,0.580,0.048
Parent Document Retrieval,0.958,1.000,0.418,0.102
Ensemble Retrieval,0.958,0.574,0.404,0.000

### Compare cost and latency across retrievers

In [68]:
import pandas as pd
cost_latency_df = pd.DataFrame()

rows = []
for ragas_eval in ragas_metrics:
    row = {
        "retriever": ragas_eval["chain_name"],
        **ragas_eval["summary"],
    }
    rows.append(row)

cost_latency_df = pd.DataFrame(rows)
cost_latency_df.round(1)

,retriever,avg_latency_ms,p95_latency_ms,avg_total_tokens,total_tokens_sum
0,Naive Retrieval,2188.5,3072.4,1554.8,18658
1,BM25 Retrieval,1379.5,2349.4,586.8,7041
2,Contextual Compression Retrieval,2166.3,2997.6,618.9,7427
3,Multi-Query Retrieval,3569.6,4317.4,1930.7,23168
4,Parent Document Retrieval,2112.2,2591.2,1180.7,14168
5,Ensemble Retrieval,4937.4,6159.1,3113.9,37367

### Retriever Analysis

Across this dataset, the simpler dense retrieval performs very well. The Naive Retrieval achieves perfect context recall with high precision, which indicates the relevant evidence is easy to retrieve. The relatively small size of this dataset is another reason why the evidence is easy to retrieve More advanced strategies don’t drasically improve recall, suggesting the RAG dataset and queries are simple and straight-forward. 

The metrics start to differ in how much noise they introduce. Naive retrieval and Parent Document retrieval have the highest noise ratings while Multi-Query and Contextual Compression strike the best balance, with both maintaining high recall and precision while achieving the lowest noise sensitivity. This means that the provided context is more accurate (less halucinations) whilei still providing high coverage. Lastly, Ensemble retrieval and Parent Document retrieval seem to trade off precision by pulling in broader context that does not add value for this dataset. 

From a cost and latency perspective, there are 3 groups. In the first, BM25 is the clear winner with the lowest latency and cost (in tokens), which is useful if these are critical concerns. Contextual Compression and Naive retrieval sit in the middle group with similar latencies and token usage. These are good choices for this dataset, especially when compared with their overall performance. In the final grouping, Multi-Query retrieval and Ensemble retrieval are significantly slower and more expensive. This is primarily due to their additional orchestration and LLM calls through multiple query generation, merging, and reranking.

Overall, these results show that, for this dataset, the simpler retrievers perform the best and have the best efficiency. This makes sense because the corpus is relatively small and easily segmented. More complex, advanced retrievers will likely perform better in larger datasets where information is sparse and from various sources.

![Retrieval Quality Analysis 2](RetrievalQualityAnalysis2.png)